<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'AccountNameController' => 'controller/AccountNameController.php',
    'AphrontURIMapper' => 'infrastructure/AphrontURIMapper.php',
    'AuthSession' => 'auth/AuthSession.php',
    'Breadcrumbs' => 'ui/Breadcrumbs.php',
    'Control' => 'ui/Control.php',
    'GoogleService' => 'google/GoogleService.php',
    'GoogleToUserMappingModel' => 'model/GoogleToUserMappingModel.php',
    'HomeBannerControl' => 'ui/HomeBannerControl.php',
    'HomeController' => 'controller/HomeController.php',
    'HomeFeaturesControl' => 'ui/HomeFeaturesControl.php',
    'IndexBannerControl' => 'ui/IndexBannerControl.php',
    'IndexController' => 'controller/IndexController.php',
    'IndexFeaturesControl' => 'ui/IndexFeaturesControl.php',
    'IndexSearchControl' => 'ui/IndexSearchControl.php',
    'LogoutController' => 'controller/LogoutController.php',
    'OAuth2CallbackController' => 'controller/OAuth2CallbackController.php',
    'PackageModel' => 'model/PackageModel.php',
    'PackageSearch' => 'google/PackageSearch.php',
    'PackagesEditController' => 'controller/PackagesEditController.php',
    'PackagesManageController' => 'controller/PackagesManageController.php',
    'ProtobuildController' => 'infrastructure/ProtobuildController.php',
    'ProtobuildEnv' => 'config/ProtobuildEnv.php',
    'RouteDelegation' => 'infrastructure/RouteDelegation.php',
  ),
  'function' => array(),
  'xmap' => array(
    'AccountNameController' => 'ProtobuildController',
    'Breadcrumbs' => 'Control',
    'Control' => array(
      'Phobject',
      'PhutilSafeHTMLProducerInterface',
    ),
    'GoogleService' => 'Phobject',
    'HomeBannerControl' => 'Control',
    'HomeController' => 'ProtobuildController',
    'HomeFeaturesControl' => 'Control',
    'IndexBannerControl' => 'Control',
    'IndexController' => 'ProtobuildController',
    'IndexFeaturesControl' => 'Control',
    'IndexSearchControl' => 'Control',
    'LogoutController' => 'ProtobuildController',
    'OAuth2CallbackController' => 'ProtobuildController',
    'PackagesEditController' => 'ProtobuildController',
    'PackagesManageController' => 'ProtobuildController',
    'ProtobuildController' => 'Phobject',
  ),
));
